# Docker compose file for Wyoming-Whisper (STT) instance. Required for LLaMaDesu backend
# Docker image built from https://github.com/chaosiris/vchaos-wyoming-whisper
# Originally sourced from https://github.com/slackr31337/wyoming-whisper-gpu. Big thank you to slackr31337!

services:
  llamadesu-wyoming-whisper:
    container_name: llamadesu-wyoming-whisper
    image: chaosiris/vchaos-wyoming-whisper:latest  
    environment:  
      - MODEL=small-int8
      - LANGUAGE=en
      - COMPUTE_TYPE=int8
      - BEAM_SIZE=5
      - HF_HUB_CACHE=/data
    ports:  
      - 10300:10300
    volumes:
      # Assumes the compose file is being ran from the /setup/docker directory. Please adjust accordingly as needed!
      - ../../src/data/stt_models:/data  
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute